### ISSUE TITLE
Interpolation problems in `DancingScript[wght].ttf`

### ISSUE THREAD

**Issue by behdad** [impallari/DancingScript#6]
Hello!

This is an automatically-generated report about possible interpolation problems in `DancingScript[wght].ttf`, as found in the Google Fonts catalog.

To download a PDF version of this report with helpful visuals of the problems, click [here](https://github.com/behdad/google-fonts-ofl-interpolatable-results/raw/d856d89bb54c39f9fcc99a44ea000e0a37367cc3/reports/DancingScript%5Bwght%5D.ttf.pdf); Or to view it on the GitHub website, click [here](https://github.com/behdad/google-fonts-ofl-interpolatable-results/blob/d856d89bb54c39f9fcc99a44ea000e0a37367cc3/reports/DancingScript%5Bwght%5D.ttf.pdf).

The report follows:
```
Glyph approxequal was not compatible:
  Masters: '', 'wght=700.0':
    Contour 0 start point differs: 0 in '', 12 in 'wght=700.0'; reversed: False
    Contour 1 start point differs: 0 in '', 12 in 'wght=700.0'; reversed: False
```

This report was generated using the `fonttools varLib.interpolatable` tool.  We understand that sometimes the tool generates false-positives.  Particularly for more complicated font designs.  If you did not find this report useful, please accept our apologies and ignore / close it.

To give feedback about this report, please file an issue or open a discussion at [fonttools](https://github.com/fonttools/fonttools).

**Comment by impallari** [comment]
Fixed for the next release. Thanks!
