### ISSUE TITLE
Capital eszett is just straight up a B instead

### ISSUE THREAD

**Issue by JapanYoshi** [impallari/DancingScript#7]
Dancing Script’s capital eszett is indistinguishable from a capital B, because the curl goes under the vertical, instead of terminating next to it.

![Screenshot_20240325_113858](https://github.com/impallari/DancingScript/assets/8707990/3ff32784-3570-41e6-8792-07679a8efc38)

In handwriting, to avoid this exact problem, a descender is added to the vertical, like this doodle.

![Screenshot_20240325_113946](https://github.com/impallari/DancingScript/assets/8707990/2242fc13-214f-4d44-9dc1-47187d369151)

For reference, see http://cinga.ch/eszett/

**Comment by impallari** [comment]
Thanks for reporting it! Will be fixed in next release.

**Comment by JapanYoshi** [comment]
![image](https://github.com/impallari/DancingScript/assets/8707990/32f76d2f-c9eb-4be1-a6a2-a565943d07ec)
This is great!
